### ISSUE TITLE
ERROR CHECKPOINT FAILED FOR HEIGHT 65000

### ISSUE THREAD

**Issue by madouz** [TheCircleFoundation/conceal-core#12]
I've compiled conceal successfully and have tried many times but keep getting 'ERROR CHECKPOINT FAILED FOR HEIGHT 65000.Check the attached image file. Looking at block explorer the 'FETCHED HASH' is correct for height 65000 while the 'EXPECTED HASH' is for a different height. I also tried deleting p2pstate.bin and resync and also resync from 0 still same error. How to fix this?

![syncerror](https://user-images.githubusercontent.com/24627386/45932459-961af880-bf7c-11e8-9402-a459a6b1bceb.jpg)

**Comment by krypt0x** [comment]
Hi madouz,

It's fixed. There was a wrong hash on the config file for block 65000.

I am sorry for any inconvenience caused. Thanks for pointing this out.

Pop in our discord and i will be happy to tip you for your troubles.

Thank you.

**Comment by krypt0x** [comment]
This issue is now sorted out and post closed.

**Comment by madouz** [comment]
Not fixed. Still got same error.

**Comment by madouz** [comment]
![error2](https://user-images.githubusercontent.com/24627386/45934343-747e3900-bf9d-11e8-8df7-84747fd5149b.png)

**Comment by krypt0x** [comment]
Yes, it is. Have you rebuild the code?

The code changes need to be rebuild to take effect, otherwise you will be using the previous code version (with the issue). If your daemon keeps stuck after rebuild, try to delete the blockdata folder (".conceal") and download data again.

**Comment by cryptokatz** [comment]
Hi,

I can confirm that it works for me. I compiled again from source, and I passed 65,000 @madouz, please check and let us know.

**Comment by madouz** [comment]
Okay it worked. Thought config was changed peer side and used the old binary. Thanks.
